common: &COMMON
  adapter: postgresql
  pool: 100
  encoding: utf8
  reconnect: true
  timeout: 15

test:
  <<: *COMMON
  database: rp_test
  username: brandon
  host:     localhost
  port:     5432

development:
  <<: *COMMON
  database: rp_development
  username: brandon
  host:     localhost
  port:     5432

staging:
  <<: *COMMON
  database: rp_staging
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>

production:
  <<: *COMMON
  database: rp_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>


# production:
#   <<: *COMMON
#   database: <%=ENV['OPENSHIFT_APP_NAME']%>
#   username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
#   password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
#   host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
#   port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
#   socket:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>
