common: &COMMON
  adapter: postgresql
  encoding: utf8
  pool: 100
  reconnect: true
  timeout: 15


test:
  <<: *COMMON
  database: rp_api_test
  username: brandon


development:
  <<: *COMMON
  database: rp_api_development
  username: brandon


production:
  <<: *COMMON
  database: rp_api_production
  username: brandon


# production:
#   <<: *COMMON
#   database: <%=ENV['OPENSHIFT_APP_NAME']%>
#   username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
#   password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
#   host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
#   port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
#   socket:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>
