common: &COMMON
  adapter: postgresql
  pool: 100
  encoding: utf8
  reconnect: true
  timeout: 15

test:
  <<: *COMMON
  database: rp_test
  username: brandon
  host:     localhost
  port:     5432

development:
  <<: *COMMON
  database: heroku_pulled
  username: brandon
  host:     localhost
  port:     5432

profile:
  <<: *COMMON
  database: rp_development
  username: brandon
  host:     localhost
  port:     5432
