# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da23715b9d7502247bb092646bde78d4ed523e624ac478a672b6a8610ca61796cc4ac77938bfce62a6527541ab2c924f3f9cc8638b24eafba94ebe0c3cd7d953

test:
  secret_key_base: feef99237c1c533250d8fa4201925443218b0f84acdffb57a177d691ec605282948613835adc49eb6abc844ed5382e39972b9181c005dbdd4d8406b9407751fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
