# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:timeout: 30
:concurrency:  5
:queues:
  - [critical, 10]
  - [default, 5]
  - [mailer, 2]
  - [cache, 1]
:limits:
  cache: 25
production:
  :concurrency: 50
staging:
  :concurrency: 50
  :verbose: true
development:
  :verbose: true
test:
  :verbose: true
